apiVersion: v1
kind: PersistentVolume
metadata:
  name: vlm # /var/lib/mongodb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/opt/k8s/vlm"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vlm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
