apiVersion: v1
kind: PersistentVolume
metadata:
  name: vlp  # /var/lib/pulp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/k8s/vlp"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vlp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
