apiVersion: v1
kind: PersistentVolume
metadata:
  name: vlq
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/opt/k8s/vlq"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vlq
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
